Repository coco-moo/final_project, pull requests merged in 2024-03, with the labels that each got.

#13 커스텀 훅 적용한 로그인 및 회원가입 페이지
  front_end/src/pages/IDPWLogin.js
  front_end/src/pages/SignUpMail.js
Labels: enhancement

#15 반응형 적용 헤더 스타일
  front_end/src/styled/Header.css
Labels: 🎨css

#16 반응형 적용 스타일 css
  front_end/src/components/PurchaseReqForm.js
  front_end/src/pages/RegRequest.js
  front_end/src/pages/RegRequest1.js
  front_end/src/pages/RegRequest2.js
  front_end/src/pages/RegRequest3.js
  front_end/src/pages/SalesHistory.js
  front_end/src/styled/Footer.css
  front_end/src/styled/PurchaseReqForm.css
  front_end/src/styled/PurchaseReqList.css
  front_end/src/styled/PurchaseRequest.css
  front_end/src/styled/RecentBooks.css
  front_end/src/styled/Title.css
Labels: 🎨css

#51 일반 로그인시 클라이언트에 쿠키저장 대신 서버쪽 세션에 저장
  back_end/models/userDB.js
  back_end/routes/userRoutes.js
  back_end/table.sql
  front_end/src/App.js
  front_end/src/hooks/api/useLogOut.js
  front_end/src/hooks/api/useLoginCheck.js
  front_end/src/pages/Main.js
  front_end/src/pages/Profile.js
  front_end/src/pages/SignUpEasy.js
  front_end/src/pages/SignUpMail.js
  front_end/src/styled/Profile.css
Labels: 👻feature

#50 로그인 판별 후 ui 변경
  front_end/src/components/Header.js
  front_end/src/hooks/api/useLogOut.js
  front_end/src/pages/Main.js
Labels: question

#61 로그인 관리 문제 수정
  front_end/src/App.js
  front_end/src/components/Header.js
  front_end/src/components/LoginContext.js
  front_end/src/hooks/api/useLoginCheck.js
  front_end/src/hooks/api/useLoginWithGoogle.js
  front_end/src/pages/Main.js
Labels: 👻feature
