Repository coco-moo/final_project, pull requests merged in 2024-04, with the labels that each got.

#62 라우터 정의
  back_end/models/SellerBook/SellerBookDB.js
  back_end/models/address/addressDB.js
  back_end/models/buyerBook/buyerBookDB.js
  back_end/models/customers/customersDB.js
  back_end/models/enquiry/enquiryDB.js
  back_end/models/orders/odersDB.js
  back_end/models/review/reviewDB.js
  back_end/models/userDB.js
  back_end/routes/userRoutes.js
  back_end/table.sql
Labels: 👻feature

#68 버튼 hover, 1440px 미만 화면에서 active CSS 수정
  front_end/src/pages/SNSLogin.js
  front_end/src/styled/App.css
  front_end/src/styled/DateInquiry.css
  front_end/src/styled/DetailConts.css
  front_end/src/styled/Purchase.css
  front_end/src/styled/PurchaseHistory.css
  front_end/src/styled/SignUp.css
Labels: 🎨css

#80 상품등록신청페이지 DB 연결 관련
  back_end/table.sql
  front_end/src/components/PurchaseReqForm.js
Labels: 👻feature

#83 구매하기페이지 DB 주소 연결
  front_end/src/components/DestForm.js
  front_end/src/components/PurDefDest.js
  front_end/src/pages/Profile.js
  front_end/src/styled/DestForm.css
  front_end/src/styled/Profile.css
  front_end/src/styled/PurDefDest.css
Labels: 🎨css, 👻feature

#121 [fix] RegRequest : bookSearch 한글키워드 및 폼 자동 입력
  .gitignore
  back_end/server.js
  back_end/table.sql
  front_end/src/components/Admin/Enquiry.js
  front_end/src/components/Admin/UserInfo.js
  front_end/src/components/PurchaseReqForm.js
  front_end/src/components/bookSearch.js
  front_end/src/pages/QuestionForm.js
  front_end/src/pages/RegRequest.js
Labels: 👻feature

#130 [fix] 구매 희망 도서 상품 등록 페이지 : PurchaseReqFrom 컴포넌트 - 입찰 마감기한 클릭 시 CSS 수정
  front_end/src/components/PurchaseReqForm.js
  front_end/src/styled/PurchaseReqForm.css
Labels: 🎨css

#132 Feacture] sales history
  back_end/table.sql
  front_end/src/components/SalesHistoryList.js
  front_end/src/pages/SalesHistory.js
  front_end/src/styled/PurchaseReqList.css
Labels: 🎨css, 👻feature

#142 구매내역 페이지 + 구매 후기 작성 페이지
  back_end/package-lock.json
  back_end/package.json
  back_end/server.js
  front_end/src/components/BookSaleBid.js
  front_end/src/components/PurInfoBox.js
  front_end/src/components/ReviewCreate.js
  front_end/src/hooks/api/useGetReviews.js
  front_end/src/hooks/api/useSellerNickname.js
  front_end/src/pages/PurchaseHistory.js
  front_end/src/pages/PurchaseReview.js
Labels: 👻feature

#154 [fix] App.js : Purchase 경로명 수정
  back_end/server.js
  front_end/src/App.js
  front_end/src/components/DestForm.js
  front_end/src/hooks/api/useUserAddr.js
  front_end/src/pages/Purchase.js
Labels: 👻feature

#159 - 구매하기/구매내역페이지 PurInfoBox 컴포넌트 분리 및 구매하기 DB 연결
  front_end/src/App.js
  front_end/src/components/DestForm.js
  front_end/src/components/PurHistInfoBox.js
  front_end/src/components/PurInfoBox.js
  front_end/src/hooks/api/usePurInfoData.js
  front_end/src/hooks/api/useUserAddr.js
  front_end/src/pages/Purchase.js
  front_end/src/pages/PurchaseHistory.js
Labels: 👻feature

#157 구매하기 페이지 DB연결
  back_end/server.js
  front_end/src/App.js
  front_end/src/components/DestForm.js
  front_end/src/components/PurInfoBox.js
  front_end/src/components/PurInfoBoxForPur.js
  front_end/src/components/ReviewCreate.js
  front_end/src/hooks/api/useBookDataByItemSellKey.js
  front_end/src/hooks/api/useBuyerInformation.js
  front_end/src/pages/IDPWLogin.js
  front_end/src/pages/Purchase.js
Labels: 👻feature

#165 [fix]카테고리별 도서리스트 -헤더 검색어 기능 추가
  front_end/src/App.js
  front_end/src/components/Header.js
  front_end/src/pages/CategoryBookLIst.js
Labels: 👻feature

#166 [fix]전체 구매 희망 도서에 대한 카테고리 추가 및 검색 기능/전역변수 정의 파일 추가
  front_end/src/components/CategoryBanner.js
  front_end/src/components/Header.js
  front_end/src/config.js
  front_end/src/pages/CategoryBookLIst.js
Labels: 👻feature

#169 [fix] CSS 수정
  front_end/src/components/CategoryBanner.js
  front_end/src/components/ProductList.js
  front_end/src/pages/CategoryBookLIst.js
  front_end/src/styled/BuyDetail.css
Labels: 🎨css

#171 [fix] Purchase페이지 : DefDestCheck.css 수정
  front_end/src/styled/DefDestCheck.css
Labels: 🎨css, 👻feature

#173 카테고리별 검색 오류 슈팅 / 판매글 등록 시 알림 기능 추가 / + css 추가
  back_end/server.js
  front_end/components/Header.js
  front_end/components/RecentBooks.js
  front_end/styled/Header.css
  front_end/styled/ImageSlider.css
  front_end/styled/RecentBooks.css
Labels: 🎨css, 👻feature

#176 [feature]내 판매글 낙찰 알림 기능 추가
  back_end/server.js
  front_end/src/components/Header.js
  front_end/src/styled/Header.css
Labels: 👻feature

#184 [fix]카테고리별 도서리스트 반응형 적용
  front_end/src/components/ProductList.js
  front_end/src/pages/CategoryBookLIst.js
Labels: 🎨css

#185 [fix]도서구매희망페이지 반응형 적용
  front_end/src/components/bookSearch.js
  front_end/src/styled/BookSearch.css
  front_end/src/styled/Header.css
  front_end/src/styled/Pagination.css
  front_end/src/styled/PurchaseReqForm.css
Labels: 🎨css

#186 [fix]카테고리 에러 메시지 가려지지않게 마진 조정
  front_end/src/styled/PurchaseReqForm.css
Labels: 🎨css

#188 [fix] BuyDetail 페이지 : DropDownSort 컴포넌트 삭제 후 해당 코드를 BuyDetail에 작성
  front_end/src/components/DropDownSort.js
  front_end/src/pages/BuyDetail.js
Labels: 👻feature

#189 [fix] 판매내역 DateInquiry 기능 적용
  front_end/src/components/DateInquiry.js
  front_end/src/components/SalesHistoryList.js
  front_end/src/pages/SalesHistory.js
Labels: 👻feature
